### PR TITLE
Performance Improvements

### PR DESCRIPTION
**Pull request by end360**
- Remove useless code from team.GetPlayers providing overall performance increase
- Optimize a lot of loops that looped over team.GetPlayers
- Use on average quicker method to determine if a team has players.
- Remove useless table.Count from pmeta:CanPickupWeapon

Tested in a local server and on a live server.

### CODE REVIEW

**Comment by khwstolle** [comment]
I am assuming this has something to do with new APIs that are available now?

The gamemode is already very well optimized - what performance increase have you been able to measure?

**Comment by end360** [comment]
> 
> 
> I am assuming this has something to do with new APIs that are available now?
> 
> The gamemode is already very well optimized - what performance increase have you been able to measure?

None of it  uses new APIs, a lot of the performance improvements are from removing useless code from loops/heavily called functions and looping over every playing and comparing team instead of looping over team.GetPlayers.

For measurements I don't have exact values because I didn't log them but I can if you'd like. If a change I tried didn't offer a sizable difference in performance I didn't add it.

**Comment by khwstolle** [comment]
Looping over team.GetPlayers should be the preferred method. If this internally just creates a new table and checks the player metamethod Team, then this would be a good point of optimization. 

Since the probability of a team change happening is much less than team.GetPlayers being called (team changes happen sporadically), I would propose the following solution to be implemented on the server:
1. make 'caching' tables for each team
2. override the player's metamethod SetTeam to insert the player in each of these tables and remove them out of their current (would suggest caching the index on the player object). This can be done as such:
```
local pmeta = FindMetaTable("Player");
local oldSetTeam = pmeta.SetTeam;
function pmeta:SetTeam(t)
    -- Check if this is relevant for us - some mods may have their own teams
    if t == TEAM_GUARD or t == TEAM_PRISONER or t == TEAM_SPECTATOR then
        -- a. Check the current team using self:Team() and some cached index, 
        -- e.g. self.JBTeamIndex, and remove from current teams table
       ....
        -- b. Add to new teams table
        ...
    end

    -- c. Call the 'old' method, setting the team
    oldSetTeam(self,t);
end
```
3. Hook the player leave event to remove them from their teamtable
4. Override team.GetPlayers in the same way as we did in (2), calling the old base method if the team is not known (admin mods, other mods, etc.)

This solution would yield a better result when our goal is to loop over a certain team, while not having to refrain from using the intuitively more logical team.GetPlayers rather than player.GetAll. It would make calling SetTeam more expensive, but this shouldn't be an issue.

**Comment by Kefta** [comment]
Make sure you pass varargs during function overrides to not conflict with other overrides.

**Comment by Kefta** [comment]
Nice one

**Pull request closed without merging**
